version: "3.8"

services:

    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment: 
            - APP_NAME=YHB
        expose: 
            - 8080
    
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports: 
            - "8084:80"